### ISSUE TITLE
https://www.114yygh.com 网站不让用了 只能小程序

### ISSUE THREAD

**Issue by shuohao** [hjwang1024/guahao114#8]
这个脚本还能升级码 小程序

**Comment by hhcol620** [comment]
北京这边很多都不好用吧，有技术牛吗

**Comment by jianmomo** [comment]
请问有解决方法吗？

**Comment by hhcol620** [comment]
> 请问有解决方法吗？

什么医院？什么科室

**Comment by jianmomo** [comment]
积水潭，脊柱外科

**Comment by jianmomo** [comment]
> > 请问有解决方法吗？
> 
> 什么医院？什么科室
积水潭，脊柱外科，大佬现在还有脚本能用吗？

**Comment by hhcol620** [comment]
热门的抢不到，目前方案都差不了太多

**Comment by jianmomo** [comment]
> 热门的抢不到，目前方案都差不了太多

小程序上抓包吗？我小程序抢了几天了，一到点就卡...界面都刷不出来。

**Comment by hhcol620** [comment]
抓包方案在看，你抓包搞得吗，加密搞出来了吗

> > 热门的抢不到，目前方案都差不了太多
> 
> 小程序上抓包吗？我小程序抢了几天了，一到点就卡...界面都刷不出来。

**Comment by jianmomo** [comment]
> 抓包方案在看，你抓包搞得吗，加密搞出来了吗
> 
> > > 热门的抢不到，目前方案都差不了太多
> > 
> > 
> > 小程序上抓包吗？我小程序抢了几天了，一到点就卡...界面都刷不出来。

没有....不是搞爬虫的....找不到开源的方案我就找黄牛了

**Comment by xiaoxinshi51** [comment]
> > 抓包方案在看，你抓包搞得吗，加密搞出来了吗
> > > > 热门的抢不到，目前方案都差不了太多
> > > 
> > > 
> > > 小程序上抓包吗？我小程序抢了几天了，一到点就卡...界面都刷不出来。
> 
> 没有....不是搞爬虫的....找不到开源的方案我就找黄牛了

你好 请问最后找到办法了吗

**Comment by hhcol620** [comment]
刷接口也没用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xiaoxinshi51 ***@***.***&gt;
发送时间: 2024年11月28日 11:46
收件人: hjwang1024/guahao114 ***@***.***&gt;
抄送: hg ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [hjwang1024/guahao114] https://www.114yygh.com 网站不让用了 只能小程序 (Issue #8)





   
抓包方案在看，你抓包搞得吗，加密搞出来了吗
   
热门的抢不到，目前方案都差不了太多
  
小程序上抓包吗？我小程序抢了几天了，一到点就卡...界面都刷不出来。
   
没有....不是搞爬虫的....找不到开源的方案我就找黄牛了
  
你好 请问最后找到办法了吗
